### ISSUE TITLE
GMCS-issue

### ISSUE THREAD

**Issue by httpwilliem** [httpwilliem/GMCS-Williem-Gomes#1]
[README](https://github.com/httpwilliem/GMCS-Williem-Berg/edit/main/README.md)
@ramidedantas

**Comment by httpwilliem** [comment]
Issue com a lista criada, professor.

**Comment by ramidedantas** [comment]
@httpwilliem o checklist? me marcou nele?

**Comment by httpwilliem** [comment]
@ramidedantas 
Sim sim, professor. O senhor deu até um like. Dei um assign agora lá no checklist para alertar.

**Comment by httpwilliem** [comment]
@ramidedantas professor atualizei o readme no formato. Poderia conferir se está certo?

**Comment by ramidedantas** [comment]
@httpwilliem adicionado, pode fechar issue.
